# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli
    commands:
      - echo "Building Angular project..."
        # ng build is the command you use when you're ready to build your app 
        # and deploy it. The CLI will analyze the application and build the
        # files, all while optimizing the application as best as it can.
      - ng build --prod
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/api-ui/ s3://my-aws-s3-bucket737 --delete